word_costs = {
    1: {"word": "Sandpaper", "cost": 8},
    2: {"word": "Oil", "cost": 10},
    3: {"word": "Steam", "cost": 15},
    4: {"word": "Acid", "cost": 16},
    5: {"word": "Gust", "cost": 18},
    6: {"word": "Boulder", "cost": 20},
    7: {"word": "Drill", "cost": 20},
    8: {"word": "Vacation", "cost": 20},
    9: {"word": "Fire", "cost": 22},
    10: {"word": "Drought", "cost": 24},
    11: {"word": "Water", "cost": 25},
    12: {"word": "Vacuum", "cost": 27},
    13: {"word": "Laser", "cost": 28},
    14: {"word": "Life Raft", "cost": 30},
    15: {"word": "Bear Trap", "cost": 32},
    16: {"word": "Hydraulic Jack", "cost": 33},
    17: {"word": "Diamond Cage", "cost": 35},
    18: {"word": "Dam", "cost": 35},
    19: {"word": "Sunshine", "cost": 35},
    20: {"word": "Mutation", "cost": 35},
    21: {"word": "Kevlar Vest", "cost": 38},
    22: {"word": "Jackhammer", "cost": 38},
    23: {"word": "Signal Jammer", "cost": 40},
    24: {"word": "Grizzly", "cost": 41},
    25: {"word": "Reinforced Steel Door", "cost": 42},
    26: {"word": "Bulldozer", "cost": 42},
    27: {"word": "Sonic Boom", "cost": 45},
    28: {"word": "Robot", "cost": 45},
    29: {"word": "Glacier", "cost": 45},
    30: {"word": "Love", "cost": 45},
    31: {"word": "Fire Blanket", "cost": 48},
    32: {"word": "Super Glue", "cost": 48},
    33: {"word": "Therapy", "cost": 48},
    34: {"word": "Disease", "cost": 50},
    35: {"word": "Fire Extinguisher", "cost": 50},
    36: {"word": "Satellite", "cost": 50},
    37: {"word": "Confidence", "cost": 50},
    38: {"word": "Absorption", "cost": 52},
    39: {"word": "Neutralizing Agent", "cost": 55},
    40: {"word": "Freeze", "cost": 55},
    41: {"word": "Encryption", "cost": 55},
    42: {"word": "Proof", "cost": 55},
    43: {"word": "Molotov Cocktail", "cost": 58},
    44: {"word": "Rainstorm", "cost": 58},
    45: {"word": "Viral Meme", "cost": 58},
    46: {"word": "War", "cost": 59},
    47: {"word": "Dynamite", "cost": 60},
    48: {"word": "Seismic Dampener", "cost": 60},
    49: {"word": "Propaganda", "cost": 60},
    50: {"word": "Explosion", "cost": 62},
    51: {"word": "Lightning", "cost": 65},
    52: {"word": "Evacuation", "cost": 65},
    53: {"word": "Flood", "cost": 67},
    54: {"word": "Lava", "cost": 68},
    55: {"word": "Reforestation", "cost": 70},
    56: {"word": "Avalanche", "cost": 72},
    57: {"word": "Earthquake", "cost": 74},
    58: {"word": "H-bomb", "cost": 75},
    59: {"word": "Dragon", "cost": 75},
    60: {"word": "Innovation", "cost": 75},
    61: {"word": "Hurricane", "cost": 76},
    62: {"word": "Tsunami", "cost": 78},
    63: {"word": "Persistence", "cost": 80},
    64: {"word": "Resilience", "cost": 85},
    65: {"word": "Terraforming Device", "cost": 89},
    66: {"word": "Anti-Virus Nanocloud", "cost": 90},
    67: {"word": "AI Kill Switch", "cost": 90},
    68: {"word": "Nanobot Swarm", "cost": 92},
    69: {"word": "Reality Resynchronizer", "cost": 92},
    70: {"word": "Cataclysm Containment Field", "cost": 92},
    71: {"word": "Solar Deflection Array", "cost": 93},
    72: {"word": "Planetary Evacuation Fleet", "cost": 94},
    73: {"word": "Antimatter Cannon", "cost": 95},
    74: {"word": "Planetary Defense Shield", "cost": 96},
    75: {"word": "Singularity Stabilizer", "cost": 97},
    76: {"word": "Orbital Laser", "cost": 98},
    77: {"word": "Time", "cost": 100}
}

beats = {
    "fire": ["Water", "Fire Extinguisher", "Fire Blanket"],
    "lion": ["Grizzly", "Bear Trap"],
    "gun": ["Kevlar Vest", "Reinforced Steel Door"],
    "flood": ["Dam"],
    "lava": ["Freeze"],
    "war": ["Peace", "Love", "Propaganda"],
    "earthquake": ["Seismic Dampener"],
    "tsunami": ["Terraforming Device"],
    "disease": ["Anti-Virus Nanocloud", "Therapy"],
    "explosion": ["Cataclysm Containment Field", "Seismic Dampener"],
    "hurricane": ["Solar Deflection Array"],
    "dragon": ["Robot", "Laser", "Orbital Laser"],
    "drought": ["Rainstorm"],
    "vacuum": ["Reality Resynchronizer"],
    "mutation": ["Neutralizing Agent"],
    "viral meme": ["Viral Meme", "Signal Jammer"],
    "fire blanket": ["Fire"],
}
