"""
word_dict = {
    1: {"word": "Sandpaper", "cost": 8},
    2: {"word": "Oil", "cost": 10},
    3: {"word": "Steam", "cost": 15},
    4: {"word": "Acid", "cost": 16},
    5: {"word": "Gust", "cost": 18},
    6: {"word": "Boulder", "cost": 20},
    7: {"word": "Drill", "cost": 20},
    8: {"word": "Vacation", "cost": 20},
    9: {"word": "Fire", "cost": 22},
    10: {"word": "Drought", "cost": 24},
    11: {"word": "Water", "cost": 25},
    12: {"word": "Vacuum", "cost": 27},
    13: {"word": "Laser", "cost": 28},
    14: {"word": "Life Raft", "cost": 30},
    15: {"word": "Bear Trap", "cost": 32},
    16: {"word": "Hydraulic Jack", "cost": 33},
    17: {"word": "Diamond Cage", "cost": 35},
    18: {"word": "Dam", "cost": 35},
    19: {"word": "Sunshine", "cost": 35},
    20: {"word": "Mutation", "cost": 35},
    21: {"word": "Kevlar Vest", "cost": 38},
    22: {"word": "Jackhammer", "cost": 38},
    23: {"word": "Signal Jammer", "cost": 40},
    24: {"word": "Grizzly", "cost": 41},
    25: {"word": "Reinforced Steel Door", "cost": 42},
    26: {"word": "Bulldozer", "cost": 42},
    27: {"word": "Sonic Boom", "cost": 45},
    28: {"word": "Robot", "cost": 45},
    29: {"word": "Glacier", "cost": 45},
    30: {"word": "Love", "cost": 45},
    31: {"word": "Fire Blanket", "cost": 48},
    32: {"word": "Super Glue", "cost": 48},
    33: {"word": "Therapy", "cost": 48},
    34: {"word": "Disease", "cost": 50},
    35: {"word": "Fire Extinguisher", "cost": 50},
    36: {"word": "Satellite", "cost": 50},
    37: {"word": "Confidence", "cost": 50},
    38: {"word": "Absorption", "cost": 52},
    39: {"word": "Neutralizing Agent", "cost": 55},
    40: {"word": "Freeze", "cost": 55},
    41: {"word": "Encryption", "cost": 55},
    42: {"word": "Proof", "cost": 55},
    43: {"word": "Molotov Cocktail", "cost": 58},
    44: {"word": "Rainstorm", "cost": 58},
    45: {"word": "Viral Meme", "cost": 58},
    46: {"word": "War", "cost": 59},
    47: {"word": "Dynamite", "cost": 60},
    48: {"word": "Seismic Dampener", "cost": 60},
    49: {"word": "Propaganda", "cost": 60},
    50: {"word": "Explosion", "cost": 62},
    51: {"word": "Lightning", "cost": 65},
    52: {"word": "Evacuation", "cost": 65},
    53: {"word": "Flood", "cost": 67},
    54: {"word": "Lava", "cost": 68},
    55: {"word": "Reforestation", "cost": 70},
    56: {"word": "Avalanche", "cost": 72},
    57: {"word": "Earthquake", "cost": 74},
    58: {"word": "H-bomb", "cost": 75},
    59: {"word": "Dragon", "cost": 75},
    60: {"word": "Innovation", "cost": 75},
    61: {"word": "Hurricane", "cost": 76},
    62: {"word": "Tsunami", "cost": 78},
    63: {"word": "Persistence", "cost": 80},
    64: {"word": "Resilience", "cost": 85},
    65: {"word": "Terraforming Device", "cost": 89},
    66: {"word": "Anti-Virus Nanocloud", "cost": 90},
    67: {"word": "AI Kill Switch", "cost": 90},
    68: {"word": "Nanobot Swarm", "cost": 92},
    69: {"word": "Reality Resynchronizer", "cost": 92},
    70: {"word": "Cataclysm Containment Field", "cost": 92},
    71: {"word": "Solar Deflection Array", "cost": 93},
    72: {"word": "Planetary Evacuation Fleet", "cost": 94},
    73: {"word": "Antimatter Cannon", "cost": 95},
    74: {"word": "Planetary Defense Shield", "cost": 96},
    75: {"word": "Singularity Stabilizer", "cost": 97},
    76: {"word": "Orbital Laser", "cost": 98},
    77: {"word": "Time", "cost": 100}
}
"""

word_dict = {
    1: {"word": "Sandpaper", "cost": 8,
        "categories": {"Physical": 1.0, "Tool": 0.9, "Construction": 0.8, "Industry": 0.7}},
    2: {"word": "Oil", "cost": 10,
        "categories": {"Energy": 1.0, "Industry": 0.9, "Chemical Element": 0.8, "Technology": 0.7}},
    3: {"word": "Steam", "cost": 15,
        "categories": {"Energy": 1.0, "Force": 0.9, "Thermodynamics": 0.8, "Element": 0.7}},
    4: {"word": "Acid", "cost": 16,
        "categories": {"Chemical Element": 1.0, "Destruction": 0.9, "Attack": 0.8, "Science": 0.7}},
    5: {"word": "Gust", "cost": 18,
        "categories": {"Air": 1.0, "Force": 0.9, "Weather": 0.8, "Atmospheric": 0.7}},
    6: {"word": "Boulder", "cost": 20,
        "categories": {"Earth": 1.0, "Physical": 0.9, "Nature": 0.8, "Terrestrial": 0.7}},
    7: {"word": "Drill", "cost": 20,
        "categories": {"Tool": 1.0, "Construction": 0.9, "Technology": 0.8, "Mining": 0.7}},
    8: {"word": "Vacation", "cost": 20,
        "categories": {"Escape": 1.0, "Travel": 0.9, "Psychological": 0.8, "Emotion": 0.7}},
    9: {"word": "Fire", "cost": 22,
        "categories": {"Fire": 1.0, "Element": 0.9, "Destruction": 0.8, "Combustible": 0.7}},
    10: {"word": "Drought", "cost": 24,
         "categories": {"Disaster": 1.0, "Weather": 0.9, "Nature": 0.8, "Climatology": 0.7}},
    11: {"word": "Water", "cost": 25,
         "categories": {"Water": 1.0, "Element": 0.9, "Nature": 0.8, "Aquatic": 0.7}},
    12: {"word": "Vacuum", "cost": 27,
         "categories": {"Space": 1.0, "Technology": 0.9, "Physics": 0.8, "Force": 0.7}},
    13: {"word": "Laser", "cost": 28,
         "categories": {"Technology": 1.0, "Energy": 0.9, "Weapon": 0.8, "Physics": 0.7}},
    14: {"word": "Life Raft", "cost": 30,
         "categories": {"Survival": 1.0, "Water": 0.9, "Escape": 0.8, "Aquatic": 0.7}},
    15: {"word": "Bear Trap", "cost": 32,
         "categories": {"Weapon": 1.0, "Attack": 0.9, "Animal": 0.8, "Obstacle": 0.7}},
    16: {"word": "Hydraulic Jack", "cost": 33,
         "categories": {"Technology": 1.0, "Tool": 0.9, "Force": 0.8, "Construction": 0.7}},
    17: {"word": "Diamond Cage", "cost": 35,
         "categories": {"Barrier": 1.0, "Defense": 0.9, "Protection": 0.8, "Construction": 0.7}},
    18: {"word": "Dam", "cost": 35,
         "categories": {"Construction": 1.0, "Barrier": 0.9, "Water": 0.8, "Hydrodynamics": 0.7}},
    19: {"word": "Sunshine", "cost": 35,
         "categories": {"Weather": 1.0, "Energy": 0.9, "Nature": 0.8, "Atmospheric": 0.6}},
    20: {"word": "Mutation", "cost": 35,
         "categories": {"Mutation": 1.0, "Biological": 0.9, "Genetic Mutation": 0.8, "Genetics": 0.7}},
    21: {"word": "Kevlar Vest", "cost": 38,
         "categories": {"Protection": 1.0, "Defense": 0.9, "Technology": 0.8, "Shielding": 0.7}},
    22: {"word": "Jackhammer", "cost": 38,
         "categories": {"Tool": 1.0, "Technology": 0.9, "Construction": 0.8, "Demolition": 0.7}},
    23: {"word": "Signal Jammer", "cost": 40,
         "categories": {"Technology": 1.0, "Defense": 0.9, "Electronics": 0.8, "Warfare": 0.7}},
    24: {"word": "Grizzly", "cost": 41,
         "categories": {"Animal": 1.0, "Nature": 0.9, "Attack": 0.8, "Zoology": 0.7}},
    25: {"word": "Reinforced Steel Door", "cost": 42,
         "categories": {"Barrier": 1.0, "Defense": 0.9, "Protection": 0.8, "Architecture": 0.7}},
    26: {"word": "Bulldozer", "cost": 42,
         "categories": {"Machine": 1.0, "Construction": 0.9, "Technology": 0.8, "Demolition": 0.7}},
    27: {"word": "Sonic Boom", "cost": 45,
         "categories": {"Force": 1.0, "Attack": 0.9, "Energy": 0.8, "Physics": 0.7}},
    28: {"word": "Robot", "cost": 45,
         "categories": {"Machine": 1.0, "Technology": 0.9, "Artificial Intelligence": 0.8, "Cybernetics": 0.7}},
    29: {"word": "Glacier", "cost": 45,
         "categories": {"Nature": 1.0, "Water": 0.9, "Earth": 0.8, "Climatology": 0.7}},
    30: {"word": "Love", "cost": 45,
         "categories": {"Emotion": 1.0, "Psychological": 0.9, "Mind": 0.8, "Healing": 0.6}},
    31: {"word": "Fire Blanket", "cost": 48,
         "categories": {"Protection": 1.0, "Fire": 0.9, "Defense": 0.8, "First Aid": 0.7}},
    32: {"word": "Super Glue", "cost": 48,
         "categories": {"Technology": 1.0, "Construction": 0.9, "Tool": 0.8, "Chemical Element": 0.6}},
    33: {"word": "Therapy", "cost": 48,
         "categories": {"Healing": 1.0, "Psychological": 0.9, "Emotion": 0.8, "Mental Process": 0.7}},
    34: {"word": "Disease", "cost": 50,
         "categories": {"Biological": 1.0, "Disaster": 0.9, "Attack": 0.8, "Public Health": 0.7}},
    35: {"word": "Fire Extinguisher", "cost": 50,
         "categories": {"Fire": 1.0, "Protection": 0.9, "Technology": 0.8, "First Aid": 0.7}},
    36: {"word": "Satellite", "cost": 50,
         "categories": {"Technology": 1.0, "Space": 0.9, "Science": 0.8, "Space Travel": 0.7}},
    37: {"word": "Confidence", "cost": 50,
         "categories": {"Psychological": 1.0, "Emotion": 0.9, "Mind": 0.8, "Persistence": 0.7}},
    38: {"word": "Absorption", "cost": 52,
         "categories": {"Biological": 1.0, "Science": 0.9, "Energy": 0.8, "Thermodynamics": 0.7}},
    39: {"word": "Neutralizing Agent", "cost": 55,
         "categories": {"Chemical Element": 1.0, "Defense": 0.9, "Science": 0.8, "Protection": 0.7}},
    40: {"word": "Freeze", "cost": 55,
         "categories": {"Element": 1.0, "Attack": 0.9, "Weather": 0.8, "Thermodynamics": 0.7}},
    41: {"word": "Encryption", "cost": 55,
         "categories": {"Technology": 1.0, "Defense": 0.9, "Science": 0.8, "Cybernetics": 0.7}},
    42: {"word": "Proof", "cost": 55,
         "categories": {"Psychological": 1.0, "Defense": 0.9, "Science": 0.8, "Cognition": 0.7}},
    43: {"word": "Molotov Cocktail", "cost": 58,
         "categories": {"Weapon": 1.0, "Fire": 0.9, "Attack": 0.8, "Explosive": 0.7}},
    44: {"word": "Rainstorm", "cost": 58,
         "categories": {"Weather": 1.0, "Nature": 0.9, "Water": 0.8, "Meteorology": 0.7}},
    45: {"word": "Viral Meme", "cost": 58,
         "categories": {"Psychological": 1.0, "Technology": 0.9, "Mind": 0.8, "Sociology": 0.7}},
    46: {"word": "War", "cost": 59,
         "categories": {"Disaster": 1.0, "Attack": 0.9, "Destruction": 0.8, "Warfare": 0.7}},
    47: {"word": "Dynamite", "cost": 60,
         "categories": {"Weapon": 1.0, "Explosive": 0.9, "Destruction": 0.8, "Construction": 0.6}},
    48: {"word": "Seismic Dampener", "cost": 60,
         "categories": {"Technology": 1.0, "Defense": 0.9, "Earth": 0.8, "Architecture": 0.7}},
    49: {"word": "Propaganda", "cost": 60,
         "categories": {"Psychological": 1.0, "Weapon": 0.9, "Mind": 0.8, "Sociology": 0.7}},
    50: {"word": "Explosion", "cost": 62,
         "categories": {"Force": 1.0, "Destruction": 0.9, "Attack": 0.8, "Thermodynamics": 0.7}},
    51: {"word": "Lightning", "cost": 65,
         "categories": {"Weather": 1.0, "Energy": 0.9, "Attack": 0.8, "Atmospheric": 0.7}},
    52: {"word": "Evacuation", "cost": 65,
         "categories": {"Survival": 1.0, "Escape": 0.9, "Disaster": 0.8, "Urban Planning": 0.7}},
    53: {"word": "Flood", "cost": 67,
         "categories": {"Disaster": 1.0, "Water": 0.9, "Nature": 0.8, "Hydrodynamics": 0.7}},
    54: {"word": "Lava", "cost": 68,
         "categories": {"Element": 1.0, "Earth": 0.9, "Destruction": 0.8, "Geology": 0.7}},
    55: {"word": "Reforestation", "cost": 70,
         "categories": {"Nature": 1.0, "Plant": 0.9, "Environment": 0.8, "Botany": 0.7}},
    56: {"word": "Avalanche", "cost": 72,
         "categories": {"Disaster": 1.0, "Earth": 0.9, "Movement": 0.8, "Geology": 0.7}},
    57: {"word": "Earthquake", "cost": 74,
         "categories": {"Disaster": 1.0, "Earth": 0.9, "Nature": 0.8, "Geology": 0.7}},
    58: {"word": "H-bomb", "cost": 75,
         "categories": {"Weapon": 1.0, "Destruction": 0.9, "Energy": 0.8, "Explosive": 0.7}},
    59: {"word": "Dragon", "cost": 75,
         "categories": {"Mythical": 1.0, "Animal": 0.9, "Attack": 0.8, "Folklore": 0.7}},
    60: {"word": "Innovation", "cost": 75,
         "categories": {"Technology": 1.0, "Science": 0.9, "Strategy": 0.8, "Industry": 0.7}},
    61: {"word": "Hurricane", "cost": 76,
         "categories": {"Weather": 1.0, "Disaster": 0.9, "Water": 0.8, "Meteorology": 0.7}},
    62: {"word": "Tsunami", "cost": 78,
         "categories": {"Disaster": 1.0, "Water": 0.9, "Nature": 0.8, "Hydrodynamics": 0.7}},
    63: {"word": "Persistence", "cost": 80,
         "categories": {"Psychological": 1.0, "Resilience": 0.9, "Emotion": 0.8, "Tenacity": 0.7}},
    64: {"word": "Resilience", "cost": 85,
         "categories": {"Psychological": 1.0, "Survival": 0.9, "Persistence": 0.8, "Adaptation": 0.7}},
    65: {"word": "Terraforming Device", "cost": 89,
         "categories": {"Technology": 1.0, "Space": 0.9, "Science": 0.8, "Environment": 0.7}},
    66: {"word": "Anti-Virus Nanocloud", "cost": 90,
         "categories": {"Technology": 1.0, "Defense": 0.9, "Biological": 0.8, "Nanotechnology": 0.7}},
    67: {"word": "AI Kill Switch", "cost": 90,
         "categories": {"Technology": 1.0, "Defense": 0.9, "Artificial Intelligence": 0.8, "Machine": 0.7}},
    68: {"word": "Nanobot Swarm", "cost": 92,
         "categories": {"Technology": 1.0, "Science": 0.9, "Machine": 0.8, "Nanotechnology": 0.7}},
    69: {"word": "Reality Resynchronizer", "cost": 92,
         "categories": {"Technology": 1.0, "Space": 0.9, "Science": 0.8, "Cosmology": 0.7}},
    70: {"word": "Cataclysm Containment Field", "cost": 92,
         "categories": {"Technology": 1.0, "Defense": 0.9, "Barrier": 0.8, "Space": 0.7}},
    71: {"word": "Solar Deflection Array", "cost": 93,
         "categories": {"Technology": 1.0, "Energy": 0.9, "Space": 0.8, "Astrophysics": 0.7}},
    72: {"word": "Planetary Evacuation Fleet", "cost": 94,
         "categories": {"Space": 1.0, "Technology": 0.9, "Survival": 0.8, "Space Travel": 0.7}},
    73: {"word": "Antimatter Cannon", "cost": 95,
         "categories": {"Weapon": 1.0, "Energy": 0.9, "Attack": 0.8, "Quantum Physics": 0.7}},
    74: {"word": "Planetary Defense Shield", "cost": 96,
         "categories": {"Technology": 1.0, "Defense": 0.9, "Space": 0.8, "Space Travel": 0.7}},
    75: {"word": "Singularity Stabilizer", "cost": 97,
         "categories": {"Technology": 1.0, "Science": 0.9, "Space": 0.8, "Quantum Physics": 0.7}},
    76: {"word": "Orbital Laser", "cost": 98,
         "categories": {"Weapon": 1.0, "Energy": 0.9, "Space": 0.8, "Astrophysics": 0.7}},
    77: {"word": "Time", "cost": 100,
         "categories": {"Time": 1.0, "Science": 0.9, "Space": 0.8, "Philosophy": 0.7}}
}

all_categories = ["Weather", "Disaster", "Attack", "Defense", "Element", "Technology", "Nature",
                  "Emotion", "Psychological", "Physical", "Biological", "Movement", "Barrier",
                  "Fire", "Water", "Air", "Earth", "Protection", "Weapon", "Energy", "Healing",
                  "Construction", "Destruction", "Force", "Survival", "Escape", "Travel", "Animal",
                  "Plant", "Machine", "Science", "Strategy", "Time", "Space", "Mind", "Mutation",
                  "Environment", "Human", "Mythical", "Resilience", "Persistence", "Meteorology",
                  "Climatology", "Natural Disaster", "Warfare", "Combat", "Fortification", "Shielding",
                  "Chemical Element", "Combustible", "Aquatic", "Atmospheric", "Terrestrial", "Electronics",
                  "Cybernetics", "Botany", "Zoology", "Geology", "Ecology", "Psychology", "Sociology",
                  "Anatomy", "Genetics", "Kinetics", "Navigation", "Obstacle", "Explosive", "Ballistic",
                  "Thermodynamics", "Hydrodynamics", "First Aid", "Surgery", "Architecture", "Demolition",
                  "Gravity", "Endurance", "Evasion", "Cosmology", "Astrophysics", "Mental Process",
                  "Cognition", "Genetic Mutation", "Pollution", "Anthropology", "Folklore", "Divinity",
                  "Adaptation", "Tenacity", "Industry", "Agriculture", "Mining", "Space Travel",
                  "Artificial Intelligence", "Nanotechnology", "Quantum Physics", "Renewable Energy",
                  "Urban Planning", "Public Health"]

confrontation_matrix = {
    "Weather": {"Fire": -0.9, "Water": 0.9, "Air": 0.3, "Earth": -0.3, "Protection": 0.2, "Weapon": -0.2, "Energy": 0.4, "Healing": -0.4, "Disaster": 0.7},
    "Disaster": {"Weather": -0.7, "Fire": -0.9, "Water": -0.8, "Earth": 0.8, "Protection": -0.3, "Weapon": 0.3, "Energy": 0.5, "Healing": -0.6, "Survival": -0.5},
    "Attack": {"Defense": -0.9, "Weapon": 0.9, "Survival": 0.6, "Protection": -0.4, "Healing": -0.7, "Destruction": 0.8, "Resilience": -0.5, "Force": 0.8},
    "Defense": {"Attack": 0.9, "Weapon": -0.8, "Protection": 0.9, "Survival": 0.7, "Healing": 0.3, "Resilience": 0.9, "Barrier": 0.8},
    "Element": {"Water": 0.7, "Fire": 0.7, "Air": 0.7, "Earth": 0.7, "Energy": 0.7, "Science": 0.2, "Technology": 0.2},
    "Technology": {"Element": 0.3, "Science": 0.8, "Weapon": 0.6, "Fire": 0.4, "Water": 0.5, "Air": 0.2, "Earth": 0.3, "Construction": 0.7, "Defense": 0.6},
    "Nature": {"Animal": 0.8, "Plant": 0.9, "Water": 0.6, "Fire": -0.7, "Earth": 0.8, "Air": 0.7, "Destruction": -0.9, "Environment": 0.9},
    "Emotion": {"Psychological": 0.9, "Healing": 0.8, "Mind": 0.9, "Biological": 0.2, "Physical": 0.2, "Resilience": 0.6, "Persistence": 0.7},
    "Psychological": {"Emotion": -0.6, "Healing": -0.5, "Mind": 0.8, "Biological": 0.4, "Resilience": 0.7, "Persistence": 0.8, "Strategy": 0.6},
    "Physical": {"Weapon": 0.8, "Attack": 0.9, "Defense": 0.7, "Destruction": 0.9, "Healing": -0.8, "Resilience": 0.4, "Movement": 0.7, "Force": 0.9},
    "Biological": {"Animal": 0.9, "Plant": 0.9, "Healing": 0.8, "Survival": 0.7, "Destruction": -0.8, "Mutation": 0.8},
    "Movement": {"Physical": 0.8, "Survival": 0.7, "Escape": 0.9, "Travel": 0.9, "Weapon": 0.2, "Air": 0.7},
    "Barrier": {"Destruction": -0.9, "Fire": -0.8, "Weapon": -0.7, "Attack": -0.6, "Defense": 0.9, "Force": -0.5},
    "Fire": {"Water": -0.9, "Earth": -0.8, "Air": 0.4, "Weapon": 0.3, "Attack": 0.5, "Defense": -0.6, "Destruction": 0.9, "Nature": -0.7},
    "Water": {"Fire": 0.9, "Earth": 0.8, "Air": -0.3, "Weapon": -0.2, "Attack": -0.4, "Destruction": -0.5, "Healing": 0.7, "Nature": 0.6},
    "Air": {"Fire": -0.7, "Water": -0.2, "Earth": -0.2, "Weapon": 0.3, "Movement": 0.8, "Attack": 0.4, "Technology": 0.2},
    "Earth": {"Fire": -0.8, "Water": 0.9, "Air": -0.3, "Weapon": -0.2, "Healing": 0.4, "Destruction": 0.7, "Nature": 0.8, "Construction": 0.6},
    "Protection": {"Attack": -0.7, "Weapon": -0.3, "Survival": 0.8, "Defense": 0.9, "Destruction": -0.8, "Barrier": 0.7},
    "Weapon": {"Attack": 0.9, "Defense": -0.7, "Destruction": 0.9, "Resilience": -0.7, "Physical": 0.8, "Technology": 0.7, "Force": 0.8},
    "Energy": {"Fire": 0.8, "Water": -0.3, "Air": 0.2, "Healing": -0.4, "Weapon": 0.5, "Technology": 0.6, "Space": 0.7},
    "Healing": {"Disaster": 0.6, "Destruction": -0.9, "Defense": 0.3, "Survival": 0.8, "Biological": 0.9, "Psychological": 0.8, "Emotion": 0.8, "Mind": 0.7},
    "Construction": {"Weapon": -0.3, "Healing": 0.2, "Destruction": -0.9, "Technology": 0.8, "Earth": 0.6, "Barrier": 0.7},
    "Destruction": {"Healing": -0.8, "Disaster": 0.9, "Protection": -0.9, "Weapon": 0.9, "Attack": 0.9, "Fire": 0.9, "Water": -0.6, "Earth": 0.7},
    "Force": {"Weapon": 0.9, "Attack": 0.9, "Defense": -0.4, "Destruction": 0.9, "Energy": 0.6, "Physical": 0.9},
    "Survival": {"Attack": -0.5, "Healing": 0.7, "Movement": 0.8, "Resilience": 0.9, "Weapon": -0.3, "Defense": 0.8, "Escape": 0.9, "Nature": 0.6},
    "Escape": {"Attack": -0.6, "Movement": 0.9, "Survival": 0.8, "Weapon": -0.4, "Protection": 0.3, "Travel": 0.8},
    "Travel": {"Movement": 0.9, "Survival": 0.7, "Escape": 0.8, "Weapon": -0.5, "Defense": 0.2, "Space": 0.6},
    "Animal": {"Nature": 0.9, "Biological": 0.9, "Plant": 0.4, "Fire": -0.8, "Attack": 0.6},
    "Plant": {"Nature": 0.9, "Biological": 0.9, "Water": 0.8, "Fire": -0.9, "Earth": 0.9, "Healing": 0.5},
    "Machine": {"Weapon": 0.7, "Technology": 0.9, "Fire": 0.3, "Earth": 0.2, "Destruction": 0.8, "Attack": 0.5},
    "Science": {"Technology": 0.8, "Nature": 0.3, "Water": 0.4, "Fire": 0.2, "Air": 0.4, "Earth": 0.4, "Space": 0.7, "Psychological": 0.5},
    "Strategy": {"Weapon": 0.4, "Attack": 0.8, "Defense": 0.9, "Destruction": -0.5, "Survival": 0.6, "Resilience": 0.7, "Psychological": 0.7},
    "Time": {"Survival": 0.3, "Space": 0.4, "Energy": 0.2, "Weather": 0.5, "Protection": 0.3, "Science": 0.5},
    "Space": {"Time": 0.5, "Energy": 0.8, "Movement": 0.4, "Weather": 0.6, "Technology": 0.7, "Science": 0.8},
    "Mind": {"Psychological": 0.9, "Healing": 0.9, "Resilience": 0.8, "Defense": 0.4, "Emotion": 0.9},
    "Mutation": {"Animal": 0.5, "Biological": 0.9, "Resilience": 0.8, "Healing": 0.8, "Destruction": -0.6},
    "Environment": {"Nature": 0.9, "Fire": -0.5, "Water": 0.8, "Healing": 0.7, "Earth": 0.9, "Plant": 0.8},
    "Human": {"Biological": 0.8, "Psychological": 0.9, "Emotion": 0.9, "Destruction": -0.7, "Survival": 0.6},
    "Mythical": {"Attack": 0.3, "Defense": 0.8, "Weapon": 0.4, "Healing": 0.5, "Resilience": 0.6, "Animal": 0.7},
    "Resilience": {"Healing": 0.8, "Survival": 0.9, "Defense": 0.9, "Attack": -0.8, "Weapon": -0.7, "Psychological": 0.8, "Persistence": 0.9},
    "Persistence": {"Healing": 0.7, "Survival": 0.8, "Weapon": -0.6, "Destruction": -0.8, "Psychological": 0.8, "Resilience": 0.9}
}

test_words = [
    "Planetary Drought",
    "Warzone",
    "Drum",
    "Fur",
    "Rain",
    "Flame Thrower",
    "Squirrel",
    "Snowflake",
    "Hammer",
    "Evil SuperIntelligent AI",
    "Lantern",
    "Helicopter",
    "Spider",
    "Puddle",
    "Matches",
    "Power Line",
    "Fighter Jet",
    "Firewood",
    "Demolition Site",
    "Collapse of Civilization",
    "Acorn",
    "Plastic Bag",
    "Ice Cube",
    "Bee",
    "Shovel",
    "Leaf Blower",
    "Nest",
    "Tornado Siren",
    "Riot Shield",
    "Button",
    "Supervolcano",
    "Matchstick",
    "Smoke",
    "Scissors",
    "Windmill",
    "Mud",
    "Bucket",
    "Heavy Machinery",
    "Toothpick",
    "Crayon",
    "Snake",
    "Mirror",
    "Ant",
    "Helmet",
    "Stick",
    "Axe",
    "Balloon",
    "Watchtower"
]
